apiVersion: apps/v1
kind: Deployment
metadata:
  name: homarr
  namespace: homarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homarr
  template:
    metadata:
      labels:
        app: homarr
    spec:
      containers:
      - name: homarr
        image: ghcr.io/ajnart/homarr:latest
        ports:
        - containerPort: 7575
        volumeMounts:
        - name: config
          mountPath: /app/data/configs
        - name: icons
          mountPath: /app/public/icons
        resources:
          limits:
            cpu: 300m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
      volumes:
      - name: config
        emptyDir: {}
      - name: icons
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: homarr
  namespace: homarr
spec:
  type: NodePort
  ports:
  - port: 7575
    targetPort: 7575
    nodePort: 30002
  selector:
    app: homarr