prometheus:
  prometheusSpec:
    replicas: 1
    retention: 1d
    resources:
      limits:
        cpu: 500m
        memory: 2Gi
      requests:
        cpu: 200m
        memory: 512Mi
    storageSpec: {}  # No persistent storage, uses emptyDir
    scrapeInterval: 5s
    evaluationInterval: 5s

alertmanager:
  alertmanagerSpec:
    replicas: 1
    retention: 24h
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    storage: {}  # No persistent storage, uses emptyDir

grafana:
  adminPassword: "admin" # Setting a known password
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  persistence:
    enabled: true
    size: 1Gi