apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-prometheus-datasource
  namespace: monitoring
data:
  prometheus-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.monitoring.svc.cluster.local
      access: proxy
      isDefault: true
