# Configuration for Pi-hole
apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-config
  namespace: networking
data:
  # Timezone setting
  TZ: "Asia/Bangkok"
  # Web interface password (change for production)
  WEBPASSWORD: "pihole"
  # Upstream DNS servers
  DNS1: "1.1.1.1"
  DNS2: "8.8.8.8"
  # Server configuration
  ServerIP: ""  # Will be auto-configured
  DHCP_ACTIVE: "false"  # Disable DHCP server