# Basic Pi-hole deployment without persistent storage
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: networking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
      - name: pihole
        # Using an older version tag that should be more stable
        image: pihole/pihole:2023.11.0
        # Add resource limits to ensure stability
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: pihole-config
              key: TZ
        - name: WEBPASSWORD
          valueFrom:
            configMapKeyRef:
              name: pihole-config
              key: WEBPASSWORD
        - name: DNS1
          valueFrom:
            configMapKeyRef:
              name: pihole-config
              key: DNS1
        - name: DNS2
          valueFrom:
            configMapKeyRef:
              name: pihole-config
              key: DNS2
        - name: ServerIP
          valueFrom:
            configMapKeyRef:
              name: pihole-config
              key: ServerIP
        - name: DHCP_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: pihole-config
              key: DHCP_ACTIVE
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 53
          name: dns-udp
          protocol: UDP