apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: phanthawasjira@gmail.com
    privateKeySecretRef:
      name: cloudflare-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: phanthawasjira@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token