# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: cloudflare-tunnel-config
#   namespace: cloudflared
# data:
#   config.yaml: |-
#     tunnel: 4afd66796bd8d801a6271d270f0337c2
#     credentials-file: /etc/cloudflared/credentials/credentials.json
#     metrics: 0.0.0.0:2000
#     no-autoupdate: true
#     ingress:
#     - hostname: monitor.phanthawas.dev
#       service: http://prometheus-grafana.monitoring.svc.cluster.local:80
#     - service: http_status:404

apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-tunnel-config
  namespace: cloudflared
data:
  config.yaml: |-
    tunnel: 4afd66796bd8d801a6271d270f0337c2
    credentials-file: /etc/cloudflared/credentials/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
    - service: http_status:200