apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-credentials
  namespace: cloudflared
type: Opaque
stringData:
  credentials.json: |-
    {
      "AccountTag": "44afd66796bd8d801a6271d270f0337c2",
      "TunnelID": "abd748b4-b338-46b6-a146-8fb0f38662ff",
      "TunnelName": "homelab",
      "TunnelSecret": "eyJhIjoiNGFmZDY2Nzk2YmQ4ZDgwMWE2MjcxZDI3MGYwMzM3YzIiLCJ0IjoiYWJkNzQ4YjQtYjMzOC00NmI2LWExNDYtOGZiMGYzODY2MmZmIiwicyI6Ik1EQTROR05oTjJJdFpHRTBPUzAwTW1Fd0xUaGhZamd0Wm1NMlpUZzFNMkkxTWpsaSJ9"
    }